version: '3.8'

services:
  server:
    build: .
    container_name: server
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: bash scripts/start_server.sh

  client:
    build: .
    container_name: client
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: bash scripts/start_client.sh
