# Используем базовый образ Node.js
FROM node:22

# Устанавливаем переменные окружения
ENV PROJECT_ROOT=/workspace
ENV SERVER_DIR=$PROJECT_ROOT/src/server

# Рабочая директория
WORKDIR $SERVER_DIR

# Устанавливаем зависимости
COPY ./src/server/package.json ./src/server/yarn.lock ./
RUN yarn install

# Копируем остальные файлы сервера (если нужно)
COPY ./src/server .

# Команда по умолчанию
CMD ["yarn", "start"]