version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    volumes:
      - ./src/client:/workspace/src/client  # Монтируем локальную директорию клиента
      - ./scripts:/workspace/scripts        # Монтируем локальные скрипты
      - ./config:/workspace/config          # Монтируем локальные конфиги
    tty: true
    stdin_open: true
    networks:
      - drone_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./src/server:/workspace/src/server  # Монтируем локальную директорию сервера
      - ./scripts:/workspace/scripts        # Монтируем локальные скрипты
      - ./config:/workspace/config          # Монтируем локальные конфиги
    networks:
      - drone_network

networks:
  drone_network:
    driver: bridge

environment:
  - DISPLAY=${DISPLAY}
volumes:
  - /tmp/.X11-unix:/tmp/.X11-unix